# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
# See also: https://github.com/marketplace/actions/bazel-action

name: Continuous Integration aarch64
on:
  # This lets us trigger manually from the UI.
  #
  # Self-hosted runners are not recommended for public repos because they would
  # run code from arbitrary pull requests so we just trigger this manually for
  # experimentation for now:
  #
  # https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners#self-hosted-runner-security-with-public-repositories
  #
  # It appears it may also be ok to do it only on push, just not on pull request; some discussion here:
  #
  # https://github.community/t/self-hosted-runner-security-with-public-repositories/17860
  workflow_dispatch:
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Bazel Test All (opt)
    runs-on: [self-hosted, linux, ARM64]
    # Bump up to 24 hours, default seems to be ~6 hours (which is definitely
    # too slow trying to do builds on a swapping Raspberry Pi 3 device with
    # 1GiB of RAM ATM for aarch64 build experiments, we'll see how Raspberry Pi
    # 4 does by comparison)
    timeout-minutes: 1440
    steps:
      - uses: actions/checkout@v2
      - name: Switch to the home directory of the self-hosted runner binary and extract the static configuration secrets
        run: cd /tmp/actions-runner && cat .credentials .credentials_rsaparams .runner
